name: end2end-asr-pytorch 
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.9.16
    - numpy=1.23.1
    - pip=22.3.1
    - pip:
      - https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp39-cp39-linux_x86_64.whl
      - ffmpeg-python==0.2.0
      - pip-chill==1.0.1
      - librosa==0.9.2
      - tqdm
      - python-Levenshtein
      - pandas
      - matplotlib
